spring.application.name=service

spring.application.name=service
spring.datasource.url=jdbc:oracle:thin:@192.167.1.45:1521:orcl
spring.datasource.username=PokemonAPIDataBase
spring.datasource.password=password1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=annabustamnte@gmail.com
spring.mail.password=fnal fdic khem aycv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.tomcat.max-part-count=100
server.tomcat.max-part-header-size =2048